### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by mpgn** [sixertoy/brackets-github-issues#3]
Is this application is depreciated ?
If I tests with this depot, I don't have any icon to the right panel.

**Comment by sixertoy** [comment]
Salut

Sur quel systeme tu tournes ? Windows ? Linux ?

**Comment by mpgn** [comment]
Windows 7 64 bits. 
Un exemple avec ton repo : 
http://i.gyazo.com/12ebe14603a18161059b73e073c4356b.png
